### ISSUE TITLE
Create CrySL rules for JSSE

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CogniCrypt#108]

**Comment by kruegers** [comment]
Please sum up here which rules you have created, the problems you faced while specifying, and the test cases you devised to check the rules.

**Comment by AndreSonntag** [comment]
**Repository: Crypto-API-Rules 
Branch: JSSE**
_Created:_
- SSLParameters
- SSLContext
- SSLEngine
- KeyManagerFactory
- KeyStoreBuilderParameters
- TrustManagerFactory
- CertPathTrustManagerParameters
- PKIXParameters
- PKIXBuilderParameters
- TrustAnchor

_Problems during the specifying:_
PKIXBuilderPramaters & PKIXParameters required  "java.util.Set<java.security.cert.TrustAnchor" as input parameter for the constructor. The expression "< ... >" wasn't defined in the grammar file. Currently we are using a temporary solution which defines the expression, but it is also possible to write "int<...>".

SSLEngine is an abstract class, which will create via "SSLContext.createSSLEngine()". The SSLEngine rule itself starts with "setEnabledCipherSuites(ciphersuites)" or "setEnabledProtocols(protocols)"

**Repository: CryptoAnalysis
Branch: master (not pushed)**
_Created test cases:_
Package: forbiddenmethods
- SSLContextTest

Package: typestate
- SSLParametersTest **[error]**
- SSLContextTest [run]
- SSLEngineTest **[error]**
- KeyManagerFactoryTest [run]
- KeyStoreBuilderParametersTest [run]
- TrustManagerFactoryTest [run]
- CertPathTrustManagerParameters [run]
- PKIXParametersTest [run]
- PKIXBuilderParametersTest **[error]** 
- TrustAnchorTest [error]

**[error]**: As previously discussed, there must be a problem regarding the state identification in the IDEALCrossingTestingFramework or the order regular expression in the rules are wrong.

@kruegers could you give me the permission for the CryptoAnalysis repository please?

**Comment by kruegers** [comment]
Thx for the update, @AndreSonntag. You have write acces to the repo now.

**Comment by kruegers** [comment]
Two rules have compilation errors: PKIXBuilderParameters and PKIXParameters. Looking at that again, I'm fairly certain that is related to <> syntax of sets. Can you please push the updated grammar to a separate branch in the crysl repo? I have given you write permissions there, too. Thanks.

**Comment by AndreSonntag** [comment]
I add the grammar in branche CryptSL/GrammarFix.

**Comment by kruegers** [comment]
I have merged the rules into the master branch. For the rest, I'll be opening a new issue.
