### ISSUE TITLE
Error markers not cleared when closing Eclipse

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CogniCrypt#112]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **Java runtime used to run eclipse:** `1.8`
* **Git branch/Commit-ID:**  `Master` / d5d24e3c3fd928eca0ff515b89ca15cd9a9870b9

### Issue description
0. Launch Eclipse
1. Create sample Java project with misuse of JCA.
2. Wait til error marker has been generated by CogniCrypt_SAST.
3. Close Eclipse.
4. Re-launch Eclipse.
5. Error markers are still present.
6. Modify code and save.
7. Wait til new error marker has been generated.

The issue is that error markers are not cleared when exiting Eclipse.

**Comment by johspaeth** [comment]
Does the bug cover the issue that even after fixing and saving the code, the old error markers and there information is still present? Which means even if I fix "ECB" to "CBC", the error marker for "ECB" will still be present.

Have you observed the same problem or shall I open a new bug?

**Comment by kruegers** [comment]
The fix might be similar, but the behaviour you describe was certainly not initially intended to be covered by this issue. Opening another issue makes sense to me.

**Comment by kruegers** [comment]
@johspaeth Can you please check whether that problem still occurs? I have pushed the current version to the update site.
