### ISSUE TITLE
CrySL Rule for javax.servlet.http.Cookie 

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CogniCrypt#159]
Create a rule for javax.servlet.http.Cookie 

A cookie must call setSecure(true) before it flows to a Response.

See [here](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-2092)

**Comment by kruegers** [comment]
\assigned @seena-mathew.

**Comment by kruegers** [comment]
The rule, for now, is available as part of the JCA rule set [here](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/JavaCryptographicArchitecture/src/Cookie.cryptsl).
