### ISSUE TITLE
Support Android API for the rules

### ISSUE THREAD

**Issue by triwater** [CROSSINGTUD/CogniCrypt#200]
I'm always frustrated when I write Android API rules or other non-standard Java API rules. Because in this condition, CogniCrypt can not compile the binary rules. 

Looking forward to your solutions or suggestions.

**Comment by johspaeth** [comment]
Hi @triwater 

when you write a CrySL rule the current project's classpath is used to resolve the classes and their methods. In this way you receive auto-completion when writing the rules. 

Try to add the Android SDK to the classpath of the project you are writing rules in.

**Comment by triwater** [comment]
@johspaeth 
thx, it works
