### ISSUE TITLE
We should move this issue tracker

### ISSUE THREAD

**Issue by ericbodden** [CROSSINGTUD/CogniCrypt#216]
Now that the repo has moved to https://github.com/eclipse-cognicrypt/CogniCrypt, we should also move this issue tracker to https://github.com/eclipse-cognicrypt/CogniCrypt/issues. Is there a way to actually move all the issues?

**Comment by johspaeth** [comment]
Good point.

I had a quick look. There is no official way, but there is an [issue mover](https://github-issue-mover.appspot.com/) that allows to create (copies) of the actual issues in a second repository. The author of al new issues is a single github user but the original authors are still referenced and a link to the original (closed) issue is added.

More info:
[https://github.com/holman/ama/issues/413](https://github.com/holman/ama/issues/413)

**Comment by abirke** [comment]
As far as I know, [transferring](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/#transferring-to-another-organization) should retain issues

**Comment by ericbodden** [comment]
@abirke I am afraid I think transferring won't be possible as the new repo already exists. Ideally we would want to transfer only the issues but I am not sure that's possible other than by the way @johspaeth described.

**Comment by kruegers** [comment]
Closing because of what @johspaeth describes [over here](https://github.com/CROSSINGTUD/CogniCrypt/issues/223#issuecomment-437661265). Thanks, @abirke for the pointer. That helped to reopen the discussion on the transfer.
