### ISSUE TITLE
Integrate UI tests into nightly build

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CogniCrypt#22]
In /src/test/java/crossing/e1/configurator/test/ui, there are five UI tests, created with the UI-testing plugin RCPTT. Right now, they work for my machine. Integrate them into the nightly build. 
This might help: https://www.eclipse.org/rcptt/documentation/userguide/maven/"

**Comment by enriozuni** [comment]
added some new RCP test cases and updated the old ones via 89ea7f4e29e78db4c2923ed86764b45bf89a3c7d

**Comment by kruegers** [comment]
Nice! Can you please give a short overwiew here what the RCPTT test cases are each doing? Thanks.

**Comment by enriozuni** [comment]
Sure. I have created and updated the UI test cases with the help of RCPTT. Currently, CogniCrypt can generate code for 7 Cryptographic tasks. Each UI test case implements the default path of generating one of the 7 Crypto tasks. Each test case follows the same stream: creates a new Java project, creates a new class, generates in that class one of the Crypto tasks, and at the end deletes the Java project. These UI test cases ensure that the default creation and generation of the Crypto tasks works as expected. Lastly, there are 7 UI test, each of them carrying the generation of one Crypto task:

     1. **EncDefault.test** (Encrypts Data using a Secret Key)
     2. **HybridEncDefault.test** (Hybrid Encryption)
     3. **JudgeTrust3PDefault.test** (Judging Trusworthingness of Third Parties)
     4. **LTADefault.test** (Securely Archives Files)
     5. **PWHashDefault.test** (Encodes Password for Secure Storage)
     6. **SecureComDefault.test** (Establish a Secure Communication Network/Channel)
     7. **SecureMPCompDefault.test** (Secures Multi-Party Computation)
