### ISSUE TITLE
Prevent one of the to be generated classes from being the output class

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CogniCrypt#96]
#### Prerequisitives
* **Git branch/Commit-ID:**  Master

### Issue description
When one re-runs the code generation and has a file opened that will be generated anew, CogniCrypt selects this file as output file. Instead, it should keep the temporary output file output.java and not move the templateUsage method.

**Comment by AndreSonntag** [comment]
Last time @CCPah have decided to fix the maven bug and afterwards he want to merge the branch.

**Comment by CCPah** [comment]
Yeah i fixed the stuff with the docker container not being able to launch guis, but i had some issues with the merge afterwards. Will get back to that later today or tomorrow morning.
